### ISSUE TITLE
A kaart template should not start at 1,1

### ISSUE THREAD

**Issue by TheodoorP** [gameoftrades/gameoftrades-library#4]
Currently, when creating a new kaart template the coordinates start at 1,1. Not only are coordinates normally measured from 0,0 but this also creates problems when comparing the coordinates themselves to the multidimensional array that the kaart terrein is stored in. 

A good example of this is an extra check I implemented today: I tried creating an ArrayList with steden in it and tried using the `getTerreinOp()` method of the kaart class. The usage I had in mind was checking whether the terrain on a specific coordinate actually had a Stad on it, however when creating a Stad object it starts counting at 1,1 whilst when using the `getTerreinOp()` method it starts counting at 0,0 due to it being an Array. 

Even though creating a second coordinate object would fix this problem this is not a nice solution in my opinion. A better solution would be either letting just the frontend use 1,1 as a starting location or starting everything from 0,0.

**Comment by ctrl-alt-dev** [comment]
Yes, specifications sometimes translate badly to computers. 

In this case the specification was [the map](https://github.com/gameoftrades/gameoftrades-student-kit/blob/master/OPDRACHT.md#voorbeeld-terreinkaart). As you can see it is one based. Which is [convenient for humans but less so for computers](https://superuser.com/questions/578292/why-do-computers-count-from-zero). The map files are one based too.

The `Kaart` on the other hand is, as you observed, zero based. 
As should `Stad` be, as it is expressed in the coordinate system of the `Kaart`.

My guess is that you should be converting coordinate systems in your implementation of the `WereldLader` :-)

**Comment by TheodoorP** [comment]
So just to double-check: the UI itself is zero-based just like all the other components aside from the map specification, right?

**Comment by ctrl-alt-dev** [comment]
Correct :)
